Fix web client tests
Fix web client tests that broke due to jQuery upgrade from 2.1.1 to
2.2.4. The tests failed with errors like:

    Error: TypeError: undefined is not a constructor (evaluating 'e.stopPropagation()') in http://localhost:30001/clients/web/static/built/girder_lib.min.js (line 10760)

which resolves to a line in jQuery.Event:

    https://github.com/jquery/jquery/blob/2.2.4/src/event.js#L613

jQuery event objects don't propagate the dataTransfer property used by
drag and drop events from the original event to the jQuery event.
Therefore, our drag and drop handlers access the dataTransfer property
on event.originalEvent. A manually constructed and triggered jQuery's
event object doesn't contain an originalEvent property unless it's
explicitly added.

With the updated jQuery, the tests failed when calling Event methods
that don't exist on our fake originalEvent object. One solution is to
create the originalEvent objects as jQuery event objects.