girder-client: Improve handling of URL part arguments. Fixes #1890
This commit follows up on PR #1823 by improving the handling
of `--host`, `--port` and `--scheme` URL part arguments.

### Better default values

By default, hostname defaults to "localhost" with scheme and port
being respectively "http" and "8080".

If value of "--host" is different from "localhost" , scheme and port
respectively default to "https" and "443".

And finally, if hostname is different from "localhost", and "--scheme"
is "http", port is "80.

This behavior allows to accommodate both
developer trying to use the instance locally or user trying to manage
data served from secured servers.

Also partially reverts 6d56e6f (girder_client: Change default "scheme" to
"https" and fix logic setting port). Since default values are better
handled, there is no need to explicitly set the scheme to "http" within
tests.

### Better error message

The client reports a clear message when both `--api-url` and
any the URL part arguments are specified. For example:

```
$ girder-cli --port 4242 --api-url http://localhost:8080/api/v1 ...
Usage: girder-cli [OPTIONS] COMMAND [ARGS]...

Error: Option "--api-url" and option "--host" are mutually exclusive.
```

### Better help message

URL by part argument are now documented in the CLI help under
"Advanced Options".


```
$ girder-cli --help
Usage: girder-cli [OPTIONS] COMMAND [ARGS]...

  Perform common Girder CLI operations.

  The CLI is particularly suited to upload (or download) large, nested
  hierarchy of data to (or from) Girder from (or into) a local directory.

  The recommended way to use credentials is to first generate an API key and
  then specify the ``api-key`` argument or set the ``GIRDER_API_KEY``
  environment variable.

  The client also supports ``username`` and ``password`` args. If only the
  ``username`` is specified, the client will prompt the user to
  interactively input his/her password.

Options:
  --api-url TEXT   RESTful API URL (e.g https://girder.example.com:443/api/v1)
  --api-key TEXT   [default: GIRDER_API_KEY env. variable]
  --username TEXT
  --password TEXT
  -h, --help       Show this message and exit.

Advanced Options:
  --host TEXT      [default: localhost]
  --scheme TEXT    [default: http if localhost else https]
  --port TEXT      [default: 8080 if localhost else 443]
  --api-root TEXT  relative path to the Girder REST API  [default: api/v1]

Commands:
  download   Download files from Girder
  localsync  Synchronize local folder with remote Girder folder
  upload     Upload files to Girder
```


Reviewed-by: Dan LaManna <dan.lamanna@kitware.com>
Reviewed-by: Jeff Baumes <jeff.baumes@kitware.com>
Reviewed-by: Roni Choudhury <roni.choudhury@kitware.com>